" *********
" Structure
" *********
"
" * Plug Manager
"
"   * Appearance
"   * Filesystem
"
" * Basics
"
"   * Clipboard
"   * Line breaks
"   * Line numbers
"   * Search
"   * Swap files
"   * Tabs
"
"     * Global
"     * Local
"
"   * Theme
"   * Whitespaces
"   * Windows
"
" * Plugins
"
"   * Airline
"   * NERDTree

" Plug Manager
" ============

call plug#begin('~/.vim/plugged')

" Appearance
" ----------

Plug 'edkolev/promptline.vim'
Plug 'flazz/vim-colorschemes'
Plug 'vim-airline/vim-airline'

" Filesystem
" ----------

Plug 'scrooloose/nerdtree'

call plug#end()

" Basics
" ======

" Clipboard
" ---------

set clipboard=unnamedplus  " enable copying / pasting from / to Vim

" Line breaks
" -----------

set textwidth=79  " break lines automatically
set nowrap        " do not wrap lines if window is small

" Line numbers
" ------------

set number          " show line numbers
set colorcolumn=80  " show ruler

" Search
" ------

set hlsearch   " highlight founded results
set incsearch  " immediately jump to first found result if possible

" clear highlights after ESC

nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" Swap files
" ----------

set directory=~/.vim/swaps//  " the only place for swaps with absolute paths

" Tabs
" ----

" Global
" ^^^^^^

set expandtab  " tabs to spaces
set smarttab   " spaces like tabs

set tabstop=4      " tab size
set shiftwidth=4   " indendation size
set softtabstop=4  " keep source tab size, but visually convert to my tab size

" Local
" ^^^^^

autocmd Filetype css setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype html setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype js setlocal tabstop=2 shiftwidth=2 softtabstop=2
autocmd Filetype rst setlocal tabstop=3 shiftwidth=3 softtabstop=3
autocmd Filetype yaml setlocal tabstop=2 shiftwidth=2 softtabstop=2

" Theme
" -----

colorscheme badwolf

" Whitespaces
" -----------

" show whitespaces at the end of line

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

" Windows
" -------

set splitbelow
set splitright

" Plugins
" =======

" Airline
" -------

let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1

set laststatus=2  " enable Airline if there is the only window

" NERDTree
" --------

" open NERDTree if no file specified

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" open NERDTree if directory specified

autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" close Neovim if last open window would be NERDTree

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
