# Alacritty 0.13.x

import = [
  "~/.config/alacritty/conf.d/cursor.toml"
  "~/.config/alacritty/conf.d/debug.toml"
  "~/.config/alacritty/conf.d/env.toml"
  "~/.config/alacritty/conf.d/font.toml"
  "~/.config/alacritty/conf.d/mouse.toml"
  "~/.config/alacritty/conf.d/scrolling.toml"
  "~/.config/alacritty/conf.d/shell.toml"
  "~/.config/alacritty/conf.d/terminal.toml"
  "~/.config/alacritty/conf.d/window.toml"
]
ipc_socket = true
live_config_reload = true
working_directory = "None"
