# Alacritty 0.13.x


import = [
  "~/.config/alacritty/conf.d/env.toml"
  "~/.config/alacritty/conf.d/font.toml"
  "~/.config/alacritty/conf.d/scrolling.toml"
  "~/.config/alacritty/conf.d/shell.toml"
  "~/.config/alacritty/conf.d/window.toml"
]
ipc_socket = true
live_config_reload = true
working_directory = "None"
