#!/bin/bash

if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# Disable freezing the terminal by CTRL+S shortcut in an interactive shell

if [[ $- == *i* ]]; then
  stty -ixon
fi

# Pyenv
# =====

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Python
# ======

export PATH="$HOME/.local/bin:$PATH"

# Pipenv
# ======

export PIPENV_VENV_IN_PROJECT=true

# Rust
# ====

export PATH="$HOME/.cargo/bin:$PATH"

# Virtualenvwrapper
# =================

export PROJECT_HOME="$HOME/github"
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"
export WORKON_HOME="$HOME/.virtualenvs"

source $HOME/.local/bin/virtualenvwrapper.sh

activate_venv() {
  if [ -e ".venv" ]; then
    if [ -f ".venv" ]; then
      workon "$(cat .venv)"
    else
      pipenv shell
    fi
  fi
}

activate_venv

function cd {
  builtin cd "$@"

  activate_venv
}
