# nOTE:
#
# Set terminal to run commands as a login shell.

source ~/.profile
source ~/.shell_prompt.sh

# Pyenv
# =====

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# Python
# ======

export PATH="$HOME/.local/bin:$PATH"

# Pipenv
# ======

export PIPENV_VENV_IN_PROJECT=true

# Virtualenvwrapper
# =================

export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/github"
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"

source $HOME/.local/bin/virtualenvwrapper.sh

activate_venv() {
  if [ -e ".venv" ]; then
    if [ -f ".venv" ]; then
      workon "$(cat .venv)"
    else
      pipenv shell
    fi
  fi
}

activate_venv

function cd {
  builtin cd "$@"

  activate_venv
}
